#language:
#   - android
#
#install:
##  - nvm install 8
##  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
##  - mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
##  - brew install yarn --ignore-dependencies
##  - brew install watchman
#  - yarn install
#
#before_script: cd android
#
#android:
#  components:
#    # Uncomment the lines below if you want to
#    # use the latest revision of Android SDK Tools
#    # - tools
#    # - platform-tools
#
#    # The BuildTools version used by your project
#    - build-tools-26.0.0
#
#    # The SDK version used to compile your project
#    - android-24
#
#    # Additional components
##    - extra-google-google_play_services
##    - extra-google-m2repository
##    - extra-android-m2repository
##    - addon-google_apis-google-19
#
#    # Specify at least one system image,
#    # if you need to run emulator(s) during your tests
#    - sys-img-armeabi-v7a-android-22
#    - sys-img-armeabi-v7a-android-17

#####NEW###
language: node_js
node_js:
  - "6.9"
sudo: false

matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      node_js: false
      install:
          - nvm install 8
          - rm -Rf "${TMPDIR}/jest_preprocess_cache"
          - brew install yarn --ignore-dependencies
          - brew install watchman
          - yarn install

      android:
        components:
          - build-tools-26.0.0
          - android-24
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android
