language: node_js
node_js:
  - "6.9"
  - "7.1"
sudo: false

matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      node_js: false

      before_install:
          - nvm install 8
          - node --version
          - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          - travis_retry sudo apt-get update -qq
          - travis_retry sudo apt-get install -y -qq yarn
          - yarn add react-native@0.48.3

      install:
          - yarn

      android:
        components:
          - build-tools-26.0.0
          - android-24
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
          - sys-img-armeabi-v7a-addon-google_apis-google-24

      before_script:
        - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
        - emulator -avd test -no-skin -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &

      script:
        - cd android && ./gradlew connectedAndroidTest
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      node_js: false
      before_install:
        - nvm install 7
        - rm -Rf "${TMPDIR}/jest_preprocess_cache"
        - node --version
        - travis_retry npm install -g yarn
        - yarn add react-native@0.48.3

      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn

      script:
        - ./scripts/objc-test-ios.sh